default: &default
adapter: mysql2
encoding: utf8mb4
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
username: athena_user
password: <%= ENV["ATHENA_DATABASE_PASSWORD"] %>
host: localhost

development:
  <<: *default
  database: auth_athena_development

test:
  <<: *default
  database: auth_athena_test

production:
  <<: *default
  database: auth_athena_production
  username: athena_user
  password: <%= ENV["ATHENA_DATABASE_PASSWORD"] %>
